PROCEDURE pr_upda (i OUT NUMBER) IS
BEGIN 
      UPDATE FNX_TELEFONOS
      SET FLAGN ='S'
	   WHERE ((SUBSTR(NUM_TELEFONO,5,3)= SUBSTR(NUM_TELEFONO,5,1)||SUBSTR(NUM_TELEFONO,5,1)|| SUBSTR(NUM_TELEFONO,5,1))
		   OR (SUBSTR(NUM_TELEFONO,4,1)= SUBSTR(NUM_TELEFONO,5,1)AND SUBSTR(NUM_TELEFONO,6,1) =SUBSTR(NUM_TELEFONO,7,1))
		   OR (SUBSTR(NUM_TELEFONO,2,3)= SUBSTR(NUM_TELEFONO,5,3))
		   OR (SUBSTR(NUM_TELEFONO,4,4)= SUBSTR(NUM_TELEFONO,4,2)||SUBSTR  (NUM_TELEFONO,4,2)))
		   OR (SUBSTR(NUM_TELEFONO,6,2)= '00')
		   OR (SUBSTR(NUM_TELEFONO,2,4)= '0000')
		   OR (SUBSTR(NUM_TELEFONO,3,1)= '5'  AND SUBSTR(NUM_TELEFONO,5,1) = '5' AND SUBSTR(NUM_TELEFONO,7,1) = '5')
		   OR (SUBSTR(NUM_TELEFONO,3,1)= '0'  AND SUBSTR(NUM_TELEFONO,5,1) = '0'  AND SUBSTR(NUM_TELEFONO,7,1) = '0' )
		   OR (SUBSTR(NUM_TELEFONO,2,2)= SUBSTR(NUM_TELEFONO,4,2) AND (SUBSTR(NUM_TELEFONO,6,1)= SUBSTR(NUM_TELEFONO,7,1)))
		   OR(SUBSTR(NUM_TELEFONO,2,2) = SUBSTR(NUM_TELEFONO,6,2) AND (SUBSTR(NUM_TELEFONO,4,1)= SUBSTR(NUM_TELEFONO,5,1)))
     	   OR(SUBSTR(NUM_TELEFONO,4,2) = SUBSTR(NUM_TELEFONO,6,2) AND(SUBSTR(NUM_TELEFONO,2,1)= SUBSTR(NUM_TELEFONO,3,1)))
		  AND NVL(FLAGN,'N') = 'N'
		  AND LENGTH(NUM_TELEFONO)=7;		  
   IF SQL%ROWCOUNT > 0 THEN  COMMIT;
      i:=NVL(SQL%ROWCOUNT,0);
   END IF;
		UPDATE FNX_TELEFONOS
		SET FLAGN ='S'
		WHERE NUM_TELEFONO IN (
			   SELECT NUM_TELEFONO from FNX_TELEFONOS
				WHERE LENGTH (NUM_TELEFONO) =7
				  AND NVL(FLAGN,'N')!='S'
				  AND TRIM(SUBSTR(NUM_TELEFONO,4,2)) = TO_CHAR(TO_NUMBER(TRIM(SUBSTR (NUM_TELEFONO,2,2))) - 1)
				  AND TRIM(SUBSTR(NUM_TELEFONO,6,2)) = TO_CHAR(TO_NUMBER(TRIM(SUBSTR (NUM_TELEFONO,4,2))) - 1 )
				UNION
			   SELECT NUM_TELEFONO from FNX_TELEFONOS
				WHERE LENGTH (NUM_TELEFONO) =7
				  AND NVL(FLAGN,'N')!='S'
				  AND TRIM(SUBSTR(NUM_TELEFONO,4,2)) = TO_CHAR(TO_NUMBER(TRIM(SUBSTR (NUM_TELEFONO,2,2))) + 1)
				  AND TRIM(SUBSTR(NUM_TELEFONO,6,2)) = TO_CHAR(TO_NUMBER(TRIM(SUBSTR (NUM_TELEFONO,4,2))) + 1 )
				UNION
			   SELECT NUM_TELEFONO from FNX_TELEFONOS
				WHERE LENGTH (NUM_TELEFONO) =7
				  AND NVL(FLAGN,'N')!='S'
				  AND TRIM(SUBSTR(NUM_TELEFONO,5,3)) = TO_CHAR(TO_NUMBER(TRIM(SUBSTR (NUM_TELEFONO,2,3))) - 1)
				UNION
			   SELECT NUM_TELEFONO from FNX_TELEFONOS
				WHERE LENGTH (NUM_TELEFONO) =7
				  AND NVL(FLAGN,'N')!='S'
				  AND TRIM(SUBSTR(NUM_TELEFONO,5,3)) = TO_CHAR(TO_NUMBER(TRIM(SUBSTR(NUM_TELEFONO,2,3))) + 1 ));
	i:=i + NVL(SQL%ROWCOUNT,0);
   IF SQL%ROWCOUNT > 0 THEN  COMMIT; END IF;
EXCEPTION
	 WHEN OTHERS THEN
           i:=0;
END pr_upda;